ARG KERNEL_VERSION=5.10.47
ARG ALPINE_VERSION=3.13

FROM linuxkit/kernel:${KERNEL_VERSION} AS ksrc

FROM alpine:${ALPINE_VERSION}

# hadolint ignore=DL3018
RUN apk --no-cache add bash curl sudo make gcc socat

COPY --from=ksrc /kernel-dev.tar /
RUN tar xf kernel-dev.tar

WORKDIR /workspace

ENTRYPOINT [ "bash" ]