name: "Run smoke tests"
description: "Runs the smoke tests for Camblet"

runs:
  using: "composite"
  steps:
    - name: Run smoke tests
      working-directory: camblet-driver
      shell: bash
      run: |
        touch /tmp/camblet.log /tmp/file-server.log /tmp/python.log
        echo "Run processes"
        sudo AGENT_METADATACOLLECTORS_DOCKER_ENABLED=true camblet agent > /tmp/camblet.log &

        ./test/smoke.sh

        echo "Stop camblet"
        sudo pkill -9 camblet

    - name: Kernel log
      if: always()
      shell: bash
      run: |
        sudo dmesg -T

    - name: Camblet agent log
      if: always()
      shell: bash
      run: |
        cat /tmp/camblet.log

    - name: File server log
      if: always()
      shell: bash
      run: |
        cat /tmp/file-server.log

    - name: Python log
      if: always()
      shell: bash
      run: |
        cat /tmp/python.log