// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dns

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD480660bDecodeSamplesDns(in *jlexer.Lexer, out *DNSTurnaroud) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "records":
			if in.IsNull() {
				in.Skip()
				out.Records = nil
			} else {
				in.Delim('[')
				if out.Records == nil {
					if !in.IsDelim(']') {
						out.Records = make([]string, 0, 4)
					} else {
						out.Records = []string{}
					}
				} else {
					out.Records = (out.Records)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Records = append(out.Records, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "latencyNS":
			out.LatencyNS = int64(in.Int64())
		case "client":
			out.Client = string(in.String())
		case "server":
			out.Server = string(in.String())
		case "responseCode":
			out.ResponseCode = uint16(in.Uint16())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD480660bEncodeSamplesDns(out *jwriter.Writer, in DNSTurnaroud) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"records\":"
		out.RawString(prefix)
		if in.Records == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Records {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"latencyNS\":"
		out.RawString(prefix)
		out.Int64(int64(in.LatencyNS))
	}
	{
		const prefix string = ",\"client\":"
		out.RawString(prefix)
		out.String(string(in.Client))
	}
	{
		const prefix string = ",\"server\":"
		out.RawString(prefix)
		out.String(string(in.Server))
	}
	{
		const prefix string = ",\"responseCode\":"
		out.RawString(prefix)
		out.Uint16(uint16(in.ResponseCode))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DNSTurnaroud) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD480660bEncodeSamplesDns(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DNSTurnaroud) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD480660bEncodeSamplesDns(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DNSTurnaroud) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD480660bDecodeSamplesDns(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DNSTurnaroud) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD480660bDecodeSamplesDns(l, v)
}
