name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout wasm-kernel-module
      with:
        submodules: recursive

    - name: Install/setup prerequisites
      run: make setup-vm

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1
    #   with:
    #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
    #     limit-access-to-actor: true

    - name: Build module
      run: make

    - name: Run module
      run: |
        make insmod
        sudo dmesg -T

    - uses: actions/checkout@v3
      name: Checkout wasm-kernel-module-cli
      with:
        submodules: recursive
        repository: cisco-open/wasm-kernel-module-cli

    - name: Build CLI
      run: make build-cli

    - name: Cleanup module
      working-directory: ../wasm-kernel-module
      run: |
        ls -larth
        pwd
        ls -larth ..
