name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout wasm-kernel-module
      with:
        submodules: recursive
        path: wasm-kernel-module

    - name: Install/setup prerequisites
      working-directory: wasm-kernel-module
      run: make setup-vm

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1
    #   with:
    #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
    #     limit-access-to-actor: true

    - name: Build the kernel module
      working-directory: wasm-kernel-module
      run: make -j$(nproc)

    # Proxywasm module loading freezes the kernel on the GitHub Actions VM
    - name: Run the kernel module
      working-directory: wasm-kernel-module 
      run: |
        make insmod-no-proxywasm
        sudo dmesg -T

    - uses: actions/checkout@v3
      name: Checkout wasm-kernel-module-cli
      with:
        submodules: recursive
        repository: cisco-open/wasm-kernel-module-cli
        path: wasm-kernel-module-cli

    - name: Build CLI
      working-directory: wasm-kernel-module-cli
      run: make build-cli

    - name: Build OPA policy module
      working-directory: wasm-kernel-module-cli
      run: make build-opa-policy-wasm

    - name: Run OPA policy module
      working-directory: wasm-kernel-module-cli
      run: |
        make load-opa-policy-wasm
        sudo dmesg -T

    - name: Cleanup module
      working-directory: wasm-kernel-module
      run: make rmmod
