name: Makefile CI

on:
  push:
    branches: [ "*" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install/setup prerequisites
      shell: bash
      run: |
        echo "uname -a"
        uname -a
        echo "pwd"
        pwd
        sudo apt-get -y install bpfcc-tools linux-headers-$(uname -r)

    - name: Run build
      run: make
