name: Makefile CI

on:
  push:
    branches: [ "*" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run build
      run: make
