name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      name: Checkout camblet-driver
      with:
        submodules: recursive
        path: camblet-driver

    - uses: actions/checkout@v4
      name: Checkout camblet
      with:
        submodules: recursive
        repository: cisco-open/camblet
        path: camblet
        fetch-depth: 0

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v5
      with:
        go-version-file: camblet/go.mod

    - name: Run camblet tests using bats-core
      working-directory: camblet-driver
      run: |
        make tests

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1
    #   with:
    #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
    #     limit-access-to-actor: true
